### PR TITLE
Update icons and add new actions

### PR DESCRIPTION
**Pull request by willnorris**
This updates the icons to use Material icons, matching the Google meet interface.  It also adds actions to leave a call, toggle meeting participants, and toggle chat sidebar.

I'm happy to break this out into multiple PRs if you'd prefer... I just did a single one because GitHub doesn't handle stacked PRs.

### CODE REVIEW

**Review by ChrisRegado — COMMENTED** [review]
Thanks for posting this! A single PR is good.

Just a few cosmetic requests for elements in the Stream Deck desktop app:
- [ ] Can we trim the whitespace around the action images? (`com.chrisregado.googlemeet.sdPlugin/images/actions/*.png`) There's quite a bit of aliasing / jagged edges in the app on non-Retina displays which seems to go away once the canvas size is 20x20px / 40x40, with the icon taking up the full space (minus any padding to get a square image). Those are the recommended image sizes in the [Elgato Style Guide](https://developer.elgato.com/documentation/stream-deck/sdk/style-guide/#asset-sizes-and-colors).
  - [ ] While we're editing those icons, the style guide also specifies that action images should be rgb(216,216,216) (#d8d8d8), although oddly it looks like that's how the app renders them anyway even with assets that are #ffffff. So it doesn't seem to make a difference in practice...
- [ ] I left some in-line capitalization changes for consistency with the other labels.

**Comment by willnorris** [comment]
gah, I spent so much time resizing the images because the [Manifest docs](https://developer.elgato.com/documentation/stream-deck/sdk/manifest/) consistent refer to "pt" rather than "px", so I went back and resized everything after doing the unit conversion!  The page you link to has the same values, but with "px" rather than "pt".  I can simply re-export from Photoshop, that's no problem.

Regarding the padding, I find that I'm often no looking at my stream deck straight on, and so without the padding the images look distorted when viewed through the edges of the plastic buttons.  And the icons for the stock system keys seem to have some visual padding as well.  What do you think?

**Comment by willnorris** [comment]
I'll also try removing the color from the category icon to see how it looks.  It does seem to render fine, but I do like complying with the style guide whenever possible.

**Comment by ChrisRegado** [comment]
> Regarding the padding, I find that I'm often no looking at my stream deck straight on, and so without the padding the images look distorted when viewed through the edges of the plastic buttons. And the icons for the stock system keys seem to have some visual padding as well. What do you think?

Yeah, the `key` icons that appear on the actual Stream Deck device looked good to me as-is. The `action` icons (which only appear in the Mac/Windows desktop app in the sidebar, where you drag an action onto a button during configuration) are the only place where padding becomes a problem.

**Comment by willnorris** [comment]
okay, please take a look.  I removed the padding from the action images and re-exported all images at the correct sizes.  And yes, this looks much better now!

**Comment by ChrisRegado** [comment]
Looks great, thanks! I'll get this merged in and upload a new release.

**Pull request merged**
